# vi: set ft=yaml :
---
input:
        basePath: '/home/ubuntu/DATA/dir/*'
        partitions: 1000
export:
        csvFile: '/home/ubuntu/DATA/export.csv'

sparkContext:
        appName: "Spark-Email-Analytics"
        masterURL:
