# vi: set ft=yaml.ansible :
---
- hosts: Master
  remote_user: ubuntu
  gather_facts: yes

  tasks:

  - name: "Task 1: Create SparkApp Directory"
    file:
      path: /home/ubuntu/SparkApp
      state: directory
      owner: ubuntu
      group: ubuntu

  - name: "Task 2: Copy sparkAppConfig.yml File to SparkApp Directory"
    copy:
      src: '../../Code/{{ item }}'
      dest: '/home/ubuntu/SparkApp/{{ item }}'
      owner: ubuntu
      group: ubuntu
      mode: 0644
    with_items:
      - sparkAppConfig.yml

  - name: "Set Fact -----> Spark Master URL"
    set_fact:
      spark_master_URL: "{{ ansible_all_ipv4_addresses | ipaddr('private') | first }}"

  - name: "Task 3: Edit sparkAppConfig.yml File"
    lineinfile:
      path: /home/ubuntu/SparkApp/sparkAppConfig.yml
      regexp: 'masterURL:'
      line: "        masterURL: \"spark://{{ spark_master_URL }}:7077\""

  - name: "Task 4: Copy SparkEmailAnalyticsApp Python Script to Spark Master"
    copy:
      src: ../../Code/SparkEmailAnalyticsApp.py
      dest: /home/ubuntu/SparkApp/SparkEmailAnalyticsApp.py
      owner: ubuntu
      group: ubuntu
      mode: 0755
